"""initial schema

Revision ID: 1d7ad2716ef4
Revises: 
Create Date: 2026-09-03 18:25:29.305694
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d7ad2716ef4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_sources',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('household_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('terms_url', sa.String(length=500), nullable=True),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('allow_download', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.String(length=80), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_expire_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_sources_household_id'), 'content_sources', ['household_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('household_id', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('child_age', sa.Integer(), nullable=True),
    sa.Column('password_salt', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_household_id'), 'users', ['household_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('household_id', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_household_id'), 'audit_events', ['household_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_type'), 'audit_events', ['resource_type'], unique=False)
    op.create_table('community_submissions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('household_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('original_url', sa.String(length=1500), nullable=False),
    sa.Column('publisher_note', sa.Text(), nullable=False),
    sa.Column('rights_note', sa.Text(), nullable=False),
    sa.Column('rights_status', sa.String(length=32), nullable=False),
    sa.Column('transfer_status', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('submitted_by', sa.String(length=40), nullable=False),
    sa.Column('transferred_by', sa.String(length=40), nullable=True),
    sa.Column('transferred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transferred_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_submissions_household_id'), 'community_submissions', ['household_id'], unique=False)
    op.create_index(op.f('ix_community_submissions_submitted_by'), 'community_submissions', ['submitted_by'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('household_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=120), nullable=False),
    sa.Column('age_from', sa.Integer(), nullable=False),
    sa.Column('age_to', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('accent', sa.String(length=20), nullable=False),
    sa.Column('cover_ref', sa.String(length=500), nullable=True),
    sa.Column('launch_url', sa.String(length=1000), nullable=True),
    sa.Column('acquisition_mode', sa.String(length=40), nullable=False),
    sa.Column('publication_status', sa.String(length=32), nullable=False),
    sa.Column('audience', sa.String(length=24), nullable=False),
    sa.Column('stimulation_level', sa.String(length=24), nullable=False),
    sa.Column('offline_activity', sa.String(length=300), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_audience'), 'content_items', ['audience'], unique=False)
    op.create_index(op.f('ix_content_items_household_id'), 'content_items', ['household_id'], unique=False)
    op.create_index(op.f('ix_content_items_kind'), 'content_items', ['kind'], unique=False)
    op.create_index(op.f('ix_content_items_publication_status'), 'content_items', ['publication_status'], unique=False)
    op.create_index(op.f('ix_content_items_title'), 'content_items', ['title'], unique=False)
    op.create_table('session_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_tokens_expires_at'), 'session_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_session_tokens_token_hash'), 'session_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_session_tokens_user_id'), 'session_tokens', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('cloud_inbox_assets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('household_id', sa.String(length=40), nullable=False),
    sa.Column('submission_id', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('inbound_ref', sa.String(length=1000), nullable=False),
    sa.Column('quarantine_ref', sa.String(length=1000), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('scan_status', sa.String(length=32), nullable=False),
    sa.Column('quarantine_status', sa.String(length=32), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=40), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['community_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_inbox_assets_household_id'), 'cloud_inbox_assets', ['household_id'], unique=False)
    op.create_index(op.f('ix_cloud_inbox_assets_sha256'), 'cloud_inbox_assets', ['sha256'], unique=True)
    op.create_table('content_assets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('content_id', sa.String(length=80), nullable=False),
    sa.Column('asset_kind', sa.String(length=24), nullable=False),
    sa.Column('storage_ref', sa.String(length=1000), nullable=False),
    sa.Column('license_ref', sa.String(length=1000), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('audience', sa.String(length=24), nullable=False),
    sa.Column('publication_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_index(op.f('ix_content_assets_content_id'), 'content_assets', ['content_id'], unique=False)
    op.create_table('content_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('household_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('content_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_events_content_id'), 'content_events', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_events_household_id'), 'content_events', ['household_id'], unique=False)
    op.create_index(op.f('ix_content_events_user_id'), 'content_events', ['user_id'], unique=False)
    op.create_table('content_requests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('household_id', sa.String(length=40), nullable=False),
    sa.Column('requester_id', sa.String(length=40), nullable=False),
    sa.Column('item_id', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('guardian_id', sa.String(length=40), nullable=True),
    sa.Column('decision_scope', sa.String(length=40), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('language_preference', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_requests_household_id'), 'content_requests', ['household_id'], unique=False)
    op.create_index(op.f('ix_content_requests_item_id'), 'content_requests', ['item_id'], unique=False)
    op.create_index(op.f('ix_content_requests_requester_id'), 'content_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_content_requests_status'), 'content_requests', ['status'], unique=False)
    op.create_index('ix_request_household_status', 'content_requests', ['household_id', 'status'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('content_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_favorite_user_content')
    )
    op.create_index(op.f('ix_favorites_content_id'), 'favorites', ['content_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('download_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('household_id', sa.String(length=40), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.Column('content_id', sa.String(length=80), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content_kind', sa.String(length=24), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('bytes_done', sa.BigInteger(), nullable=False),
    sa.Column('expected_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('manifest_ref', sa.String(length=300), nullable=True),
    sa.Column('rights_note', sa.Text(), nullable=False),
    sa.Column('proof_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['content_requests.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_download_jobs_household_id'), 'download_jobs', ['household_id'], unique=False)
    op.create_index(op.f('ix_download_jobs_scheduled_at'), 'download_jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_download_jobs_source_id'), 'download_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_download_jobs_stage'), 'download_jobs', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_jobs_stage'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_source_id'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_scheduled_at'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_household_id'), table_name='download_jobs')
    op.drop_table('download_jobs')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_content_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_request_household_status', table_name='content_requests')
    op.drop_index(op.f('ix_content_requests_status'), table_name='content_requests')
    op.drop_index(op.f('ix_content_requests_requester_id'), table_name='content_requests')
    op.drop_index(op.f('ix_content_requests_item_id'), table_name='content_requests')
    op.drop_index(op.f('ix_content_requests_household_id'), table_name='content_requests')
    op.drop_table('content_requests')
    op.drop_index(op.f('ix_content_events_user_id'), table_name='content_events')
    op.drop_index(op.f('ix_content_events_household_id'), table_name='content_events')
    op.drop_index(op.f('ix_content_events_content_id'), table_name='content_events')
    op.drop_table('content_events')
    op.drop_index(op.f('ix_content_assets_content_id'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index(op.f('ix_cloud_inbox_assets_sha256'), table_name='cloud_inbox_assets')
    op.drop_index(op.f('ix_cloud_inbox_assets_household_id'), table_name='cloud_inbox_assets')
    op.drop_table('cloud_inbox_assets')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_session_tokens_user_id'), table_name='session_tokens')
    op.drop_index(op.f('ix_session_tokens_token_hash'), table_name='session_tokens')
    op.drop_index(op.f('ix_session_tokens_expires_at'), table_name='session_tokens')
    op.drop_table('session_tokens')
    op.drop_index(op.f('ix_content_items_title'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_publication_status'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_kind'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_household_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_audience'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_community_submissions_submitted_by'), table_name='community_submissions')
    op.drop_index(op.f('ix_community_submissions_household_id'), table_name='community_submissions')
    op.drop_table('community_submissions')
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_household_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_household_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_content_sources_household_id'), table_name='content_sources')
    op.drop_table('content_sources')
    # ### end Alembic commands ###
