import type { CloudSubmission, ContentItem, ContentRequest, DownloadJob } from './types'

const image = (id: string) => '/covers/' + id + '.jpg'

export const contentItems: ContentItem[] = [
  {
    id: 'bluey',
    title: 'Bluey',
    subtitle: 'Keepy Uppy · 英语故事',
    kind: 'video',
    language: 'English',
    age: '4–7 岁',
    duration: '8 min',
    description: '把一个普通下午变成一场全家都能参与的想象游戏。自然的日常口语，温柔又有力量。',
    tags: ['家庭关系', '日常英语', '想象力'],
    accent: '#e8b84b',
    cover: image('photo-1502082553048-f009c37129b9'),
    progress: 64,
    featured: true,
    source: '官方入口 · 家长精选',
    offlineActivity: '把一个家庭小游戏搬到客厅',
  },
  {
    id: 'numberblocks',
    title: 'Numberblocks',
    subtitle: 'The Terrible Twos · 英语数学',
    kind: 'video',
    language: 'English',
    age: '4–6 岁',
    duration: '5 min',
    description: '用节奏和重复把数量、分解与加法变成一段好记的音乐故事。',
    tags: ['数感', '重复句式', '低刺激'],
    accent: '#77b5a5',
    cover: image('photo-1516627145497-ae6968895b74'),
    source: 'CBeebies · 官方入口',
    offlineActivity: '用积木表示一个数字关系',
  },
  {
    id: 'puffin-rock',
    title: 'Puffin Rock',
    subtitle: 'The New Neighbour · 英语自然',
    kind: 'video',
    language: 'English',
    age: '4–7 岁',
    duration: '7 min',
    description: '海岛上的小故事，旁白清楚、节奏舒缓，适合睡前和第一次英语观看。',
    tags: ['自然观察', '睡前', '听力'],
    accent: '#75a8cf',
    cover: image('photo-1500534623283-312aade485b7'),
    source: '官方播出平台',
    offlineActivity: '找出家附近三种鸟或树',
  },
  {
    id: 'great-movie',
    title: '《大闹天宫》',
    subtitle: '中国动画美术片 · 亲子共看',
    kind: 'video',
    language: '中文 / 少对白',
    age: '5–8 岁',
    duration: '18 min',
    description: '色彩、音乐和动作设计都极具辨识度。分段观看，给孩子留下观察画面和讲故事的空间。',
    tags: ['中国美术', '音乐', '神话'],
    accent: '#e6735e',
    cover: image('photo-1531058020387-3be344556be6'),
    source: '正版片源 · 家长精选',
    offlineActivity: '画一张自己设计的云纹',
  },
  {
    id: 'gruffalo',
    title: 'The Gruffalo',
    subtitle: '绘本 · 英语共读',
    kind: 'book',
    language: 'English',
    age: '4–7 岁',
    duration: '12 min',
    description: '押韵、重复和充满想象的森林旅程。适合先听、再看图复述，不必逐句翻译。',
    tags: ['押韵', '绘本', '复述'],
    accent: '#9a7bb4',
    cover: image('photo-1513159446162-54eb8bdaa79b'),
    source: '正版绘本 / 图书馆',
    offlineActivity: '为森林角色画一张角色卡',
  },
  {
    id: 'tuanyuan',
    title: '《团圆》',
    subtitle: '中文绘本 · 亲子阅读',
    kind: 'book',
    language: '中文',
    age: '4–7 岁',
    duration: '15 min',
    description: '从一个孩子的视角看春节和家人团聚，画面克制，适合慢慢观察细节。',
    tags: ['家庭', '节日文化', '审美'],
    accent: '#d88a63',
    cover: image('photo-1511895426328-dc8714191300'),
    source: '纸书 / 正版电子书',
    offlineActivity: '讲一讲家里最喜欢的节日',
  },
  {
    id: 'audio-story',
    title: '晚安电台 · 森林来信',
    subtitle: '有声故事 · 轻柔聆听',
    kind: 'audio',
    language: '中文',
    age: '4–8 岁',
    duration: '22 min',
    description: '适合睡前或画画时听的一期短故事。没有画面，也能练习在脑中构建场景。',
    tags: ['有声书', '想象力', '睡前'],
    accent: '#6a91b9',
    cover: image('photo-1519681393784-d120267933ba'),
    source: 'Audiobookshelf · 家庭音频库',
    offlineActivity: '听完画出你想象的森林',
  },
  {
    id: 'gcompris',
    title: 'GCompris',
    subtitle: '数学与逻辑 · 离线互动',
    kind: 'game',
    language: '中文 / English',
    age: '4–8 岁',
    duration: '15 min',
    description: '一组可以自然结束的启蒙活动，覆盖数感、逻辑、时钟、键盘和科学。',
    tags: ['数学', '逻辑', '离线'],
    accent: '#5e9b8d',
    cover: image('photo-1499750310107-5fef28a66643'),
    source: '官方项目 · 儿童设备',
    offlineActivity: '把今天学到的规则讲给家长听',
  },
  {
    id: 'scratchjr',
    title: 'ScratchJr',
    subtitle: '做一段自己的小动画',
    kind: 'create',
    language: '中文 / English',
    age: '5–7 岁',
    duration: '20 min',
    description: '让孩子用角色、动作和声音讲一个自己编的小故事，作品默认只保存在家庭里。',
    tags: ['编程', '表达', '创作'],
    accent: '#ef8b58',
    cover: image('photo-1516321318423-f06f85e504b3'),
    source: '官方应用 · 儿童设备',
    offlineActivity: '给作品录一句旁白',
  },
  {
    id: 'wild-discovery',
    title: '周末观察任务',
    subtitle: '去发现 · 户外小挑战',
    kind: 'discover',
    language: '中文',
    age: '4–8 岁',
    duration: '30 min',
    description: '带着一张小任务卡离开屏幕：找三种叶子，听一种鸟叫，或者画下一个有趣的影子。',
    tags: ['户外', '观察', '亲子'],
    accent: '#87a75b',
    cover: image('photo-1473445361085-b9a07f55608b'),
    source: '家庭自制任务',
    offlineActivity: '拍一张照片或带回一片叶子',
  },
  {
    id: 'shaun',
    title: 'Shaun the Sheep',
    subtitle: '视觉喜剧 · 少对白',
    kind: 'video',
    language: '少对白',
    age: '5–8 岁',
    duration: '7 min',
    description: '用动作、节奏和音乐讲故事。适合全家一起笑，但看后要提醒孩子不模仿危险动作。',
    tags: ['视觉叙事', '音乐', '幽默'],
    accent: '#c6a15b',
    cover: image('photo-1534528741775-53994a69daeb'),
    source: '官方入口 · 家长精选',
    offlineActivity: '用三张图讲清楚一个笑点',
  },
]

export const initialRequests: ContentRequest[] = [
  {
    id: 'req-101',
    itemId: 'great-movie',
    childName: '儿童账户',
    reason: '想看孙悟空的云',
    createdAt: '今天 16:42',
    status: 'pending',
  },
  {
    id: 'req-102',
    itemId: 'scratchjr',
    childName: '儿童账户',
    reason: '我想做一个会飞的故事',
    createdAt: '今天 15:08',
    status: 'pending',
  },
  {
    id: 'req-103',
    itemId: 'audio-story',
    childName: '儿童账户',
    reason: '睡前想听森林故事',
    createdAt: '昨天 20:16',
    status: 'pending',
  },
]

export const initialJobs: DownloadJob[] = [
  {
    id: 'job-01',
    title: '《团圆》绘本套装',
    kind: 'book',
    status: 'review',
    progress: 100,
    size: '48 MB',
    source: '家庭投递箱',
    eta: '等待审核',
  },
  {
    id: 'job-02',
    title: '森林来信 · 第 03 集',
    kind: 'audio',
    status: 'downloading',
    progress: 68,
    size: '214 MB',
    source: '自有音频库',
    eta: '约 12 分钟',
  },
  {
    id: 'job-03',
    title: 'Bluey · S02E04',
    kind: 'video',
    status: 'queued',
    progress: 0,
    size: '1.2 GB',
    source: '官方授权文件',
    eta: '今晚 02:00',
  },
  {
    id: 'job-04',
    title: '社区分享 · 英语绘本练习',
    kind: 'book',
    status: 'failed',
    progress: 42,
    size: '96 MB',
    source: '候选箱',
    eta: '许可待复核',
  },
]

export const initialSubmissions: CloudSubmission[] = [
  {
    id: 'sub-01',
    title: '老师整理：自然拼读卡片',
    source: '百度网盘',
    note: '发布页注明课堂自用，等待家长确认转存',
    status: 'candidate',
    createdAt: '今天 14:28',
  },
  {
    id: 'sub-02',
    title: '开源小游戏：小小星球',
    source: '创作者网站',
    note: '已转存到家庭投递箱，正在扫描包哈希',
    status: 'review',
    createdAt: '昨天 22:10',
  },
]
